image:
  name: docker.justbetter.nl/pipeline:laravel-php84
  username: $DOCKER_REGISTRY_USERNAME
  password: $DOCKER_REGISTRY_PASSWORD

definitions:
  steps:
    - step: &setup
        name: Setup
        runs-on:
          - self.hosted
        caches:
          - composer
        script:
          - composer config http-basic.repo.justbetter.nl $REPO_USERNAME $REPO_PASSWORD
          - composer install
        artifacts:
          - vendor/**

    - step: &analyse
        name: Analyse
        runs-on:
          - self.hosted
        script:
          - composer analyse

    - step: &style
        name: Style
        runs-on:
          - self.hosted
        script:
          - composer dumpautoload 2>&1 | grep -q "does not comply with psr-4 autoloading standard." && exit 1
          - composer style

    - step: &tests
        name: Tests
        runs-on:
          - self.hosted
        script:
          - composer test

    - step: &coverage
        name: Coverage
        runs-on:
          - self.hosted
        script:
          - composer coverage

pipelines:
  pull-requests:
    '**':
      - step: *setup
      - parallel:
        - step: *tests
        - step: *analyse
        - step: *style
        - step: *coverage
  branches:
    master:
      - step: *setup
      - parallel:
        - step: *tests
        - step: *analyse
        - step: *style
        - step: *coverage
